### ISSUE TITLE
Google issue on login if user already exists?

### ISSUE THREAD

**Issue by daverees4** [daveconservatoire/dcsite-cljs#4]
Error: ER_DUP_ENTRY: Duplicate entry '' for key 'username'
    at Query.Sequence._packetToError (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)
    --------------------
    at Protocol._enqueue (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/davidrees/Developer/dcex-cljs/node_modules/mysql/lib/Connection.js:208:25)
    at /Users/davidrees/Developer/dcex-cljs/node_modules/knex/lib/dialects/mysql/index.js:92:18
    at tryCatcher (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/promise.js:71:37)
    at Client._query (/Users/davidrees/Developer/dcex-cljs/node_modules/knex/lib/dialects/mysql/index.js:88:12)
    at Client.query (/Users/davidrees/Developer/dcex-cljs/node_modules/knex/lib/client.js:136:24)
    at Runner.<anonymous> (/Users/davidrees/Developer/dcex-cljs/node_modules/knex/lib/runner.js:115:24)
    at Runner.tryCatcher (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/util.js:26:23)
    at Runner.query (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/davidrees/Developer/dcex-cljs/node_modules/knex/lib/runner.js:43:21
    at /Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/using.js:176:30
    at tryCatcher (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/davidrees/Developer/dcex-cljs/node_modules/bluebird/js/main/promise.js:584:18)

**Comment by daverees4** [comment]
Working now
